-- Camera Rental System Database Dump
-- Generated by Antigravity AI

-- Users Data
INSERT INTO Users (id, username, password, email, role, createdAt, updatedAt) VALUES (1, 'admin', 'password123', 'admin@camera.com', 'admin', '2026-04-09T08:56:01.100Z', '2026-04-09T08:56:01.100Z');
INSERT INTO Users (id, username, password, email, role, createdAt, updatedAt) VALUES (2, 'sadsdas', 'google-auth-simulated', 'sadsdas@gmail.com', 'customer', '2026-04-09T08:58:08.239Z', '2026-04-09T08:58:08.239Z');
INSERT INTO Users (id, username, password, email, role, createdAt, updatedAt) VALUES (3, 'grace1', '1234', 'dfdsfsdfs@gmail.com', 'customer', '2026-04-09T09:06:15.287Z', '2026-04-09T09:06:15.287Z');

-- Cameras Data
INSERT INTO Cameras (id, model_name, brand, daily_rate, image, stock, status, createdAt, updatedAt) VALUES (1, 'A7III', 'Sony', 800, 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=400', 3, 'available', '2026-04-09T08:56:01.095Z', '2026-04-09T09:06:34.346Z');
INSERT INTO Cameras (id, model_name, brand, daily_rate, image, stock, status, createdAt, updatedAt) VALUES (2, 'EOS R5', 'Canon', 1500, 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&q=80&w=400', 2, 'available', '2026-04-09T08:56:01.095Z', '2026-04-09T08:56:01.095Z');
INSERT INTO Cameras (id, model_name, brand, daily_rate, image, stock, status, createdAt, updatedAt) VALUES (3, 'X-T4', 'Fujifilm', 700, 'https://images.unsplash.com/photo-1532971295325-1e434de54dc3?auto=format&fit=crop&q=80&w=400', 3, 'available', '2026-04-09T08:56:01.095Z', '2026-04-09T08:56:01.095Z');
INSERT INTO Cameras (id, model_name, brand, daily_rate, image, stock, status, createdAt, updatedAt) VALUES (4, 'Z6 II', 'Nikon', 900, 'https://images.unsplash.com/photo-1521575034604-e53f19e4a3aa?auto=format&fit=crop&q=80&w=400', 4, 'available', '2026-04-09T08:56:01.095Z', '2026-04-09T08:56:01.095Z');

-- Promotions Data
INSERT INTO Promotions (id, code, discount_percent, expiry_date, createdAt, updatedAt) VALUES (1, 'DISCOUNT10', 10, '2026-12-31T00:00:00.000Z', '2026-04-09T08:56:01.106Z', '2026-04-09T08:56:01.106Z');

-- Bookings Data
INSERT INTO Bookings (id, CameraId, UserId, PromotionId, start_date, end_date, total_price, status, createdAt, updatedAt) VALUES (1, null, null, NULL, '2026-04-09', '2026-04-10', 1600, 'confirmed', '2026-04-09T08:58:16.070Z', '2026-04-09T08:58:16.070Z');
INSERT INTO Bookings (id, CameraId, UserId, PromotionId, start_date, end_date, total_price, status, createdAt, updatedAt) VALUES (2, null, null, NULL, '2026-04-10', '2026-04-11', 1600, 'confirmed', '2026-04-09T09:06:22.333Z', '2026-04-09T09:06:34.341Z');

