const { Category, Customer, Equipment, Rental, RentalDetail, Payment, Return } = require('../models');
const fs = require('fs');
const path = require('path');

async function exportToSQL() {
    try {
        console.log('--- Starting SQL Export (Legacy ER Model) ---');
        let sqlContent = '-- Camera Rental System Database Dump (New ER Model)\n';
        sqlContent += '-- Generated by Antigravity AI\n\n';

        // Helper to escape strings
        const esc = (str) => str ? str.replace(/'/g, "''") : '';

        // 1. Categories
        const categories = await Category.findAll();
        sqlContent += '-- Categories Data\n';
        for (const c of categories) {
            sqlContent += `INSERT INTO Categories (id, CategoryName, createdAt, updatedAt) VALUES (${c.id}, '${esc(c.CategoryName)}', '${c.createdAt.toISOString()}', '${c.updatedAt.toISOString()}');\n`;
        }
        sqlContent += '\n';

        // 2. Customers
        const customers = await Customer.findAll();
        sqlContent += '-- Customers Data\n';
        for (const c of customers) {
            sqlContent += `INSERT INTO Customers (id, FirstName, LastName, Phone, Email, Address, username, password, role, createdAt, updatedAt) VALUES (${c.id}, '${esc(c.FirstName)}', '${esc(c.LastName)}', '${esc(c.Phone)}', '${esc(c.Email)}', '${esc(c.Address)}', '${esc(c.username)}', '${esc(c.password)}', '${esc(c.role)}', '${c.createdAt.toISOString()}', '${c.updatedAt.toISOString()}');\n`;
        }
        sqlContent += '\n';

        // 3. Equipment
        const equipments = await Equipment.findAll();
        sqlContent += '-- Equipment Data\n';
        for (const e of equipments) {
            sqlContent += `INSERT INTO Equipment (id, ModelName, Brand, SerialNumber, DailyRate, ImageURL, Status, CategoryId, createdAt, updatedAt) VALUES (${e.id}, '${esc(e.ModelName)}', '${esc(e.Brand)}', '${esc(e.SerialNumber)}', ${e.DailyRate}, '${esc(e.ImageURL)}', '${esc(e.Status)}', ${e.CategoryId}, '${e.createdAt.toISOString()}', '${e.updatedAt.toISOString()}');\n`;
        }
        sqlContent += '\n';

        // 4. Rentals
        const rentals = await Rental.findAll();
        sqlContent += '-- Rentals Data\n';
        for (const r of rentals) {
            sqlContent += `INSERT INTO Rentals (id, CustomerId, RentalDate, TotalAmount, RentalStatus, createdAt, updatedAt) VALUES (${r.id}, ${r.CustomerId}, '${r.RentalDate.toISOString()}', ${r.TotalAmount}, '${esc(r.RentalStatus)}', '${r.createdAt.toISOString()}', '${r.updatedAt.toISOString()}');\n`;
        }
        sqlContent += '\n';

        // 5. RentalDetails
        const details = await RentalDetail.findAll();
        sqlContent += '-- RentalDetails Data\n';
        for (const d of details) {
            sqlContent += `INSERT INTO RentalDetails (id, RentalId, EquipmentId, StartDate, EndDate, SubTotal, createdAt, updatedAt) VALUES (${d.id}, ${d.RentalId}, ${d.EquipmentId}, '${d.StartDate}', '${d.EndDate}', ${d.SubTotal}, '${d.createdAt.toISOString()}', '${d.updatedAt.toISOString()}');\n`;
        }
        sqlContent += '\n';

        // 6. Payments
        const payments = await Payment.findAll();
        sqlContent += '-- Payments Data\n';
        for (const p of payments) {
            sqlContent += `INSERT INTO Payments (id, RentalId, PaymentMethod, Amount, PaymentDate, createdAt, updatedAt) VALUES (${p.id}, ${p.RentalId}, '${esc(p.PaymentMethod)}', ${p.Amount}, '${p.PaymentDate.toISOString()}', '${p.createdAt.toISOString()}', '${p.updatedAt.toISOString()}');\n`;
        }

        const outputPath = path.join(__dirname, '../backup_data.sql');
        fs.writeFileSync(outputPath, sqlContent);
        
        console.log(`Successfully exported to: ${outputPath}`);
        process.exit(0);
    } catch (error) {
        console.error('Export failed:', error);
        process.exit(1);
    }
}

exportToSQL();
